# Generated by Django 5.0.1 on 2024-02-07 16:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('type', models.CharField(choices=[('Услуги', 'Услуги'), ('Отели', 'Отели')])),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, unique=True, verbose_name='Имя пользователя')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='ID Telegram')),
                ('register_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-register_at',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, unique=True, verbose_name='Имя пользователя')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='ID Telegram')),
                ('register_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ('-register_at',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('max_price', models.PositiveIntegerField(verbose_name='Максимальная цена')),
                ('min_price', models.PositiveIntegerField(verbose_name='Минимальная цена')),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=3, verbose_name='Фотографии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='bot.category', verbose_name='Категория')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='bot.region', verbose_name='Район')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='bot.seller', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('max_price', models.PositiveIntegerField(verbose_name='Максимальная цена')),
                ('min_price', models.PositiveIntegerField(verbose_name='Минимальная цена')),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=3, verbose_name='Фотографии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bot.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bot.seller', verbose_name='Владелец')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bot.region', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
            },
        ),
    ]
