from aiogram.fsm.state import StatesGroup, State


class Form(StatesGroup):
    who = State()
    correct_who = State()
    check_who = State()
    position = State()
    name = State()
    name_service = State()
    type_position = State()
    photo = State()
    photo_get = State()
    phone = State()
    description = State()
    min_money = State()
    max_money = State()
    address = State()
    get_district = State()
    check_position_hotel = State()
    check_position_service = State()
    correct_position = State()
    check_photo = State()
    correct_name = State()
    check_name = State()
    correct_type_position = State()
    correct_type_position_service = State()
    check_type_position = State()
    check_type_position_service = State()
    correct_photo = State()
    correct_number = State()
    check_number = State()
    correct_description = State()
    check_description = State()
    correct_min_money = State()
    check_min_money = State()
    correct_max_money = State()
    check_max_money = State()
    correct_address = State()
    check_address = State()
    correct_get_district = State()
    check_get_district = State()
